Repository fan-maum/fanplus-front, pull requests merged in 2023-09, with the labels that each got.

#65 [feat/community] 커뮤니티 게시판 기초 작업
  src/api/Community.ts
  src/components/organisms/CommunityBoardWrapper.tsx
  src/components/templates/CommunityBoardTemplate.tsx
  src/components/templates/CommunityPageTemplate.tsx
  src/hooks/useLanguage.ts
  src/pages/api/community/board.ts
  src/pages/ko/community/board.tsx
  src/pages/ko/community/board/[boardIndex].tsx
  src/pages/vi/community/board.tsx
  src/pages/vi/community/board/[boardIndex].tsx
  src/pages/zh-CN/community/board.tsx
  src/pages/zh-CN/community/board/[boardIndex].tsx
  src/types/common.ts
  src/types/community.ts
Labels: feature

#67 [feat/community] 커뮤니티 게시판 작업
  src/api/Community.ts
  src/components/atoms/IconFilter.tsx
  src/components/atoms/IconMyPost.tsx
  src/components/atoms/IconPopular.tsx
  src/components/atoms/IconPopularBlack.tsx
  src/components/atoms/IconWrite.tsx
  src/components/modals/CommunityLanguageModal.tsx
  src/components/molecules/CommunityBoardArticle.tsx
  src/components/molecules/CommunityBoardTopNavi.tsx
  src/components/molecules/PaginationBase.tsx
  src/components/organisms/CommunityBoardPagination.tsx
  src/components/organisms/VotePagination.tsx
  src/components/templates/CommunityBoardTemplate.tsx
  src/components/templates/CommunityPageTemplate.tsx
  src/hooks/useLanguage.ts
  src/pages/api/community/board.ts
  src/pages/api/community/boardTopic.ts
  src/pages/en/community/board.tsx
  src/pages/en/community/board/[boardIndex]/index.tsx
  src/pages/en/community/board/[boardIndex]/mypost.tsx
  src/pages/en/community/index.tsx
  src/pages/es/community/board.tsx
  src/pages/es/community/board/[boardIndex]/index.tsx
  src/pages/es/community/board/[boardIndex]/mypost.tsx
  src/pages/es/community/index.tsx
  src/pages/in/community/board.tsx
  src/pages/in/community/board/[boardIndex]/index.tsx
  src/pages/in/community/board/[boardIndex]/mypost.tsx
  src/pages/in/community/index.tsx
  src/pages/ja/community/board.tsx
  src/pages/ja/community/board/[boardIndex]/index.tsx
  src/pages/ja/community/board/[boardIndex]/mypost.tsx
  src/pages/ja/community/index.tsx
  src/pages/ko/community/board/[boardIndex].tsx
  src/pages/ko/community/board/[boardIndex]/index.tsx
  src/pages/ko/community/board/[boardIndex]/mypost.tsx
  src/pages/ko/community/index.tsx
  src/pages/vi/community/board/[boardIndex].tsx
  src/pages/vi/community/board/[boardIndex]/index.tsx
  src/pages/vi/community/board/[boardIndex]/mypost.tsx
  src/pages/vi/community/index.tsx
  src/pages/zh-CN/community/board/[boardIndex].tsx
  src/pages/zh-CN/community/board/[boardIndex]/index.tsx
  src/pages/zh-CN/community/board/[boardIndex]/mypost.tsx
  src/pages/zh-CN/community/index.tsx
  src/pages/zh-TW/community/board.tsx
  src/pages/zh-TW/community/board/[boardIndex]/index.tsx
  src/pages/zh-TW/community/board/[boardIndex]/mypost.tsx
  src/pages/zh-TW/community/index.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/community.ts
  src/types/textTypes.ts
  src/utils/util.ts
Labels: feature

#68 [feat/community] search board page
  package.json
  public/icons/icon_search.svg
  src/components/atoms/CustomScrollTabBar.tsx
  src/components/molecules/community/CommunityBoardItem.tsx
  src/components/molecules/community/CommunityBoardSearchInput.tsx
  src/components/organisms/community/CommunityBoardFilterTab.tsx
  src/components/organisms/community/CommunityBoardSearchInputWrapper.tsx
  src/components/organisms/community/CommunitySearchBoardPagination.tsx
  src/components/organisms/community/CommunitySearchBoardWrapper.tsx
  src/components/templates/CommunityPageTemplate.tsx
  src/pages/ko/community/index.tsx
  yarn.lock
Labels: feature

#70 [feat/community] 게시물, 최근 방문 게시판 없을 경우 화면 작업 완료
  src/components/atoms/GradientButton.tsx
  src/components/atoms/Language.tsx
  src/components/modals/CommunityLanguageModal.tsx
  src/components/molecules/CommunityBoardArticle.tsx
  src/components/molecules/CommunityBoardLangSelector.tsx
  src/components/molecules/CommunityBoardTopNavi.tsx
  src/components/organisms/CommunityBoardPagination.tsx
  src/components/organisms/community/CommunityBoardNoPost.tsx
  src/components/organisms/community/CommunityNoRecentBoard.tsx
  src/components/templates/CommunityBoardTemplate.tsx
  src/components/templates/CommunityMyPostTemplate.tsx
  src/components/templates/CommunityPageTemplate.tsx
  src/pages/api/community/withoutUserId/board.ts
  src/pages/api/community/withoutUserId/home.ts
  src/pages/en/community/board/[boardIndex]/mypost.tsx
  src/pages/es/community/board/[boardIndex]/mypost.tsx
  src/pages/in/community/board/[boardIndex]/mypost.tsx
  src/pages/ja/community/board/[boardIndex]/mypost.tsx
  src/pages/ko/community/board/[boardIndex]/mypost.tsx
  src/pages/vi/community/board/[boardIndex]/mypost.tsx
  src/pages/zh-CN/community/board/[boardIndex]/mypost.tsx
  src/pages/zh-TW/community/board/[boardIndex]/mypost.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/textTypes.ts
Labels: feature

#81 [feat/community] QA 개선 사항 및 게시글 posting api 로직 변경
  src/api/Community.ts
  src/components/modals/CommunityLanguageModal.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/community/CommunityBoardArticle.tsx
  src/components/molecules/community/CommunityBoardLangSelector.tsx
  src/components/molecules/community/EditorTopicSet.tsx
  src/components/organisms/community/CommunityBoardNoticeBanner.tsx
  src/components/organisms/community/CommunityPostDetail.tsx
  src/components/templates/CommunityBoardTemplate.tsx
  src/components/templates/CommunityMyPostTemplate.tsx
  src/components/templates/PostEditorTemplate.tsx
  src/editor/module/FileUploader.tsx
  src/editor/screen/FullEditor.tsx
  src/middleware.ts
  src/pages/api/community/editBoardArticle.ts
  src/pages/api/community/editorFileUpload.ts
  src/pages/api/community/postBoardArticle.ts
  src/pages/api/community/unAuth/post.ts
  src/pages/en/community/board/[boardIndex]/index.tsx
  src/pages/en/community/board/[boardIndex]/write.tsx
  src/pages/es/community/board/[boardIndex]/index.tsx
  src/pages/es/community/board/[boardIndex]/write.tsx
  src/pages/in/community/board/[boardIndex]/index.tsx
  src/pages/in/community/board/[boardIndex]/write.tsx
  src/pages/ja/community/board/[boardIndex]/index.tsx
  src/pages/ja/community/board/[boardIndex]/write.tsx
  src/pages/ko/community/board/[boardIndex]/index.tsx
  src/pages/ko/community/board/[boardIndex]/write.tsx
  src/pages/vi/community/board/[boardIndex]/index.tsx
  src/pages/vi/community/board/[boardIndex]/write.tsx
  src/pages/zh-CN/community/board/[boardIndex]/index.tsx
  src/pages/zh-CN/community/board/[boardIndex]/write.tsx
  src/pages/zh-TW/community/board/[boardIndex]/index.tsx
  src/pages/zh-TW/community/board/[boardIndex]/write.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/community.ts
  src/types/textTypes.ts
Labels: improvements

#84 [feat/community] editor 보완
  src/components/templates/CommunityBoardTemplate.tsx
  src/components/templates/CommunityMyPostTemplate.tsx
  src/components/templates/VoteDetailLayout.tsx
  src/editor/screen/FullEditor.tsx
  src/pages/api/community/postBoardArticle.ts
  src/pages/en/community/board/[boardIndex]/index.tsx
  src/pages/en/community/board/[boardIndex]/mypost.tsx
  src/pages/es/community/board/[boardIndex]/index.tsx
  src/pages/es/community/board/[boardIndex]/mypost.tsx
  src/pages/in/community/board/[boardIndex]/index.tsx
  src/pages/in/community/board/[boardIndex]/mypost.tsx
  src/pages/ja/community/board/[boardIndex]/index.tsx
  src/pages/ja/community/board/[boardIndex]/mypost.tsx
  src/pages/ko/community/board/[boardIndex]/index.tsx
  src/pages/ko/community/board/[boardIndex]/mypost.tsx
  src/pages/vi/community/board/[boardIndex]/index.tsx
  src/pages/vi/community/board/[boardIndex]/mypost.tsx
  src/pages/zh-CN/community/board/[boardIndex]/index.tsx
  src/pages/zh-CN/community/board/[boardIndex]/mypost.tsx
  src/pages/zh-TW/community/board/[boardIndex]/index.tsx
  src/pages/zh-TW/community/board/[boardIndex]/mypost.tsx
Labels: bug, feature

#89 [feat/community] 로그인 체킹 로직 (api error handling) 추가
  src/components/atoms/CommunityModalButton.tsx
  src/components/templates/VoteDetailLayout.tsx
  src/pages/api/community/post.ts
  src/pages/en/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/en/community/board/[boardIndex]/write.tsx
  src/pages/es/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/es/community/board/[boardIndex]/write.tsx
  src/pages/in/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/in/community/board/[boardIndex]/write.tsx
  src/pages/ja/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/ja/community/board/[boardIndex]/write.tsx
  src/pages/ko/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/ko/community/board/[boardIndex]/write.tsx
  src/pages/vi/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/vi/community/board/[boardIndex]/write.tsx
  src/pages/zh-CN/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/zh-CN/community/board/[boardIndex]/write.tsx
  src/pages/zh-TW/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/zh-TW/community/board/[boardIndex]/write.tsx
  src/utils/loginErrorHandler.ts
Labels: improvements

#90 [develop] 로그인 체킹 로직 추가 (api error handling)
  src/components/atoms/CommunityModalButton.tsx
  src/components/templates/VoteDetailLayout.tsx
  src/pages/api/community/post.ts
  src/pages/en/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/en/community/board/[boardIndex]/write.tsx
  src/pages/es/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/es/community/board/[boardIndex]/write.tsx
  src/pages/in/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/in/community/board/[boardIndex]/write.tsx
  src/pages/ja/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/ja/community/board/[boardIndex]/write.tsx
  src/pages/ko/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/ko/community/board/[boardIndex]/write.tsx
  src/pages/vi/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/vi/community/board/[boardIndex]/write.tsx
  src/pages/zh-CN/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/zh-CN/community/board/[boardIndex]/write.tsx
  src/pages/zh-TW/community/board/[boardIndex]/[postIndex]/edit.tsx
  src/pages/zh-TW/community/board/[boardIndex]/write.tsx
  src/utils/loginErrorHandler.ts
Labels: improvements

#91 [feat/community] qa3차 추가사항
  src/components/atoms/CommunityModalButton.tsx
  src/components/atoms/NavBox.tsx
  src/components/templates/CommunityBoardTemplate.tsx
  src/editor/screen/FullEditor.tsx
Labels: design

#93 [develop] qa3차 합본 (댓글 업데이트 제외)
  src/components/atoms/CommunityModalButton.tsx
  src/components/atoms/NavBox.tsx
  src/components/molecules/community/CommentPopover.tsx
  src/components/molecules/community/CommunityPostInfoState.tsx
  src/components/molecules/community/CommunityPostTopNavi.tsx
  src/components/organisms/community/CommunityPostInfo.tsx
  src/components/organisms/community/SearchScrollTabBar.tsx
  src/components/templates/CommunityBoardTemplate.tsx
  src/editor/screen/FullEditor.tsx
Labels: bug
