Repository fan-maum/fanplus-front, pull requests merged in 2023-07, with the labels that each got.

#2 [develop] vote page api 연동
  package-lock.json
  package.json
  public/icons/icon_paginationArrow.png
  src/api/Vote.ts
  src/components/molecules/VoteListTab.tsx
  src/components/molecules/VoteTitle.tsx
  src/components/organisms/VoteList.tsx
  src/components/organisms/VoteListItem.tsx
  src/components/organisms/VotePagination.tsx
  src/components/templates/VoteTemplate.tsx
  src/pages/votes.tsx
  src/styles/globals.css
  yarn.lock
Labels: feature

#3 [develop] vote page SEO, mediaQuery 설정
  package.json
  src/api/Vote.ts
  src/components/molecules/VoteListTab.tsx
  src/components/molecules/VoteTitle.tsx
  src/components/organisms/MobileVotePagination.tsx
  src/components/organisms/VoteList.tsx
  src/components/organisms/VoteListItem.tsx
  src/components/organisms/VotePagination.tsx
  src/components/organisms/VotePaginationDetail.tsx
  src/components/templates/VoteTemplate.tsx
  src/hooks/useInterval.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/api/votes.ts
  src/pages/index.tsx
  src/pages/votes.tsx
  src/styles/globals.css
  src/utils/util.ts
  yarn.lock
Labels: improvements

#9 [develop] 에러핸들링, header navBar 추가
  src/api/Vote.ts
  src/components/molecules/VoteListTab.tsx
  src/components/organisms/VotePagination.tsx
  src/pages/api/votes.ts
  src/pages/votes.tsx
Labels: feature

#8 Layout Emotion 적용 완료
  src/components/layout/Footer.tsx
  src/components/layout/Language.tsx
  src/components/layout/LanguageBox.tsx
  src/components/layout/LanguageContainer.tsx
  src/components/layout/MainLogo.tsx
  src/components/layout/NavBar.tsx
  src/components/layout/NavContainer.tsx
  src/components/layout/PageBox.tsx
  src/components/layout/ServiceBox.tsx
  src/components/layout/SideBar.tsx
  src/components/layout/styles/Footer.module.css
  src/components/layout/styles/Language.module.css
  src/components/layout/styles/LanguageBox.module.css
  src/components/layout/styles/LanguageContainer.module.css
  src/components/layout/styles/MainLogo.module.css
  src/components/layout/styles/NavBar.module.css
  src/components/layout/styles/NavContainer.module.css
  src/components/layout/styles/PageBox.module.css
  src/components/layout/styles/ServiceBox.module.css
  src/components/layout/styles/SideBar.module.css
Labels: design

#6 메인 페이지 Emotion 적용 완료
  src/components/mainPage/AppLink.tsx
  src/components/mainPage/AppStoreIcon.tsx
  src/components/mainPage/Carousel.tsx
  src/components/mainPage/MainPage.tsx
  src/components/mainPage/PlayStoreIcon.tsx
  src/components/mainPage/styles/AppLink.module.css
  src/components/mainPage/styles/Carousel.module.css
  src/components/mainPage/styles/MainPage.module.css
Labels: design

#11 [emotion작업] design 세부 사항 수정
  public/icons/icon_down.svg
  public/icons/언어팩.svg
  src/components/atoms/IconArrowDown.tsx
  src/components/layout/LanguageBox.tsx
  src/components/layout/LanguageContainer.tsx
  src/components/layout/NavBar.tsx
  src/components/layout/NavContainer.tsx
  src/components/layout/ServiceBox.tsx
  src/components/layout/SideBar.tsx
  src/components/mainPage/MainPage.tsx
  src/components/molecules/FAQNavBarTitle.tsx
  src/components/molecules/QuestionBox.tsx
  src/components/organisms/BusinessInfo.tsx
  src/components/organisms/FAQNavBar.tsx
  src/styles/DefaultProps.ts
  src/texts/ko.ts
Labels: design

#13 [develop] feat: add rewrites fallback
  next.config.js
  src/components/molecules/VoteListTab.tsx
Labels: feature

#14 [develop] 스타일 및 form api 변경 등의 수정 사항
  src/components/layout/Footer.tsx
  src/components/mainPage/MainPage.tsx
  src/components/organisms/BusinessFormHandle.tsx
Labels: design

#16 [develop] VoteListTab 상단 짤림 문제(top 속성값 변경) 및 ios 글자깨짐 문제
  src/components/molecules/VoteListTab.tsx
  src/styles/globals.css
Labels: design

#19 [폴더구조변경] mainpage 폴더 구조 변경 완료
  src/components/atoms/IconAppStore.tsx
  src/components/atoms/IconCircle.tsx
  src/components/atoms/IconPlayStore.tsx
  src/components/molecules/AppLink.tsx
  src/components/organisms/Carousel.tsx
  src/components/templates/MainPageTemplate.tsx
  src/pages/en/index.tsx
  src/pages/es/index.tsx
  src/pages/in/index.tsx
  src/pages/index.tsx
  src/pages/ja/index.tsx
  src/pages/vi/index.tsx
  src/pages/zh-rCN/index.tsx
  src/pages/zh-rTW/index.tsx
Labels: documentation

#15 [폴더구조변경] layout 폴더 구조 변경
  src/components/atoms/Language.tsx
  src/components/atoms/MainLogo.tsx
  src/components/atoms/NavBox.tsx
  src/components/layout/PageBox.tsx
  src/components/molecules/Footer.tsx
  src/components/molecules/LanguageBox.tsx
  src/components/molecules/LanguageContainer.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/NavContainer.tsx
  src/components/molecules/SideBar.tsx
  src/components/organisms/Layout.tsx
  src/pages/business.tsx
  src/pages/en/business.tsx
  src/pages/en/faq.tsx
  src/pages/en/index.tsx
  src/pages/en/votes.tsx
  src/pages/es/business.tsx
  src/pages/es/faq.tsx
  src/pages/es/index.tsx
  src/pages/es/votes.tsx
  src/pages/faq.tsx
  src/pages/in/business.tsx
  src/pages/in/faq.tsx
  src/pages/in/index.tsx
  src/pages/in/votes.tsx
  src/pages/index.tsx
  src/pages/ja/business.tsx
  src/pages/ja/faq.tsx
  src/pages/ja/index.tsx
  src/pages/ja/votes.tsx
  src/pages/vi/business.tsx
  src/pages/vi/faq.tsx
  src/pages/vi/index.tsx
  src/pages/vi/votes.tsx
  src/pages/votes.tsx
  src/pages/zh-rCN/business.tsx
  src/pages/zh-rCN/faq.tsx
  src/pages/zh-rCN/index.tsx
  src/pages/zh-rCN/votes.tsx
  src/pages/zh-rTW/business.tsx
  src/pages/zh-rTW/faq.tsx
  src/pages/zh-rTW/index.tsx
  src/pages/zh-rTW/votes.tsx
  src/types/contextTypes.ts
Labels: documentation

#28 [develop] document: eslintrc no-console rules 추가
  .eslintrc
  package.json
  src/components/molecules/VoteListTab.tsx
  src/components/molecules/VoteTitle.tsx
  src/components/molecules/voteDetail/VoteStarState.tsx
  src/components/organisms/BusinessFormHandle.tsx
  src/components/organisms/VoteListItem.tsx
  src/components/organisms/VotePagination.tsx
  src/components/organisms/voteDetail/VoteDetailHeader.tsx
  src/components/organisms/voteDetail/VoteDetailInfo.tsx
  src/components/organisms/voteDetail/VoteDetailItem.tsx
  src/components/organisms/voteDetail/VoteDetailList.tsx
  src/components/organisms/voteDetail/VoteDetailListItem.tsx
  src/components/organisms/voteDetail/VoteDetailPrizeList.tsx
  src/components/templates/VoteDetailLayout.tsx
  src/components/templates/VoteLayout.tsx
  src/hooks/useLanguage.ts
  src/pages/api/voteDetail.ts
  src/utils/util.ts
  yarn.lock
Labels: improvements
