Repository fan-maum/fanplus-front, pull requests merged in 2023-08, with the labels that each got.

#30 [develop] 수정: SVG height 오류
  src/components/atoms/IconArrowDown.tsx
Labels: design

#23 [develop] 쿠키와 미들웨어를 통한 다국어처리 자동화
  package.json
  src/components/atoms/Language.tsx
  src/components/molecules/LanguageContainer.tsx
  src/hooks/useLanguage.ts
  src/middleware.ts
  src/pages/ko/business.tsx
  src/pages/ko/faq.tsx
  src/pages/ko/index.tsx
  src/pages/ko/voteDetail.tsx
  src/pages/ko/votes.tsx
  src/pages/zh-CN/business.tsx
  src/pages/zh-CN/faq.tsx
  src/pages/zh-CN/index.tsx
  src/pages/zh-CN/voteDetail.tsx
  src/pages/zh-CN/votes.tsx
  src/pages/zh-TW/business.tsx
  src/pages/zh-TW/faq.tsx
  src/pages/zh-TW/index.tsx
  src/pages/zh-TW/voteDetail.tsx
  src/pages/zh-TW/votes.tsx
  src/pages/zh-rCN/business.tsx
  src/pages/zh-rCN/faq.tsx
  src/pages/zh-rCN/index.tsx
  src/pages/zh-rTW/business.tsx
  src/pages/zh-rTW/faq.tsx
  src/pages/zh-rTW/index.tsx
  src/store/voteLangState.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/utils/setLangCookie.ts
  yarn.lock
Labels: documentation, feature

#32 [develop] 로그인 및 회원가입 모달 창
  package.json
  src/components/atoms/IconAppStore.tsx
  src/components/atoms/IconArrowLeft.tsx
  src/components/atoms/IconBack.tsx
  src/components/atoms/IconCheckButton.tsx
  src/components/atoms/IconFanPlus.tsx
  src/components/atoms/IconGoogle.tsx
  src/components/atoms/LoginButtons/AppleLoginButton.tsx
  src/components/atoms/LoginButtons/BaseLoginButton.tsx
  src/components/atoms/LoginButtons/GoogleLoginButton.tsx
  src/components/molecules/LoginModal.tsx
  src/components/molecules/SignUpModal.tsx
  src/components/organisms/Layout.tsx
  src/components/templates/MainPageTemplate.tsx
  src/pages/api/auth/callback/apple.ts
  src/pages/api/auth/callback/google.ts
  src/pages/api/auth/login/apple.ts
  src/pages/api/auth/login/google.ts
  src/types/contextTypes.ts
  yarn.lock
Labels: feature

#31 [develop] voteDetail page shareModal
  package-lock.json
  package.json
  public/icons/Icon_Link.svg
  public/icons/Icon_More.svg
  public/icons/Icon_backArrow.svg
  public/icons/icon_Kakao.svg
  public/icons/icon_Twitter.svg
  public/icons/icon_back.svg
  src/components/atoms/BackButton.tsx
  src/components/atoms/RankProfile.tsx
  src/components/atoms/ShareButton.tsx
  src/components/atoms/ShareButtonWithIcon.tsx
  src/components/modals/CompletedShareModal.tsx
  src/components/modals/VoteDetailShareModal.tsx
  src/components/molecules/VoteListTab.tsx
  src/components/molecules/VoteTitle.tsx
  src/components/molecules/VoteTitleImage.tsx
  src/components/molecules/voteDetail/VoteStarState.tsx
  src/components/organisms/VoteListItem.tsx
  src/components/organisms/voteDetail/VoteDetailHeader.tsx
  src/components/organisms/voteDetail/VoteDetailInfo.tsx
  src/components/organisms/voteDetail/VoteDetailList.tsx
  src/components/organisms/voteDetail/VoteDetailListItem.tsx
  src/components/templates/VoteDetailLayout.tsx
  src/hooks/useCopyText.ts
  src/pages/_app.tsx
  src/pages/en/voteDetail.tsx
  src/pages/es/voteDetail.tsx
  src/pages/in/voteDetail.tsx
  src/pages/ja/voteDetail.tsx
  src/pages/ko/voteDetail.tsx
  src/pages/vi/voteDetail.tsx
  src/pages/voteDetail.tsx
  src/pages/votes.tsx
  src/pages/zh-CN/voteDetail.tsx
  src/pages/zh-TW/voteDetail.tsx
  src/store/shareContent.ts
  src/store/voteLangState.ts
  src/styles/Colors.ts
  src/styles/globals.css
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/index.d.ts
  src/utils/util.ts
  yarn.lock
Labels: feature

#34 [develop] voteDetailPage => add vote modal
  src/components/atoms/Chip.tsx
  src/components/atoms/VoteModalButton.tsx
  src/components/modals/CommonModal.tsx
  src/components/modals/VoteBlockModal.tsx
  src/components/modals/VoteDoneModal.tsx
  src/components/modals/VoteProcessModal.tsx
  src/components/molecules/VoteModalText.tsx
  src/components/templates/VoteDetailLayout.tsx
  src/styles/Colors.ts
Labels: feature

#35 [develop] vote multi-language
  src/components/modals/CommonModal.tsx
  src/components/modals/VoteBlockModal.tsx
  src/components/modals/VoteDetailShareModal.tsx
  src/components/modals/VoteDoneModal.tsx
  src/components/modals/VoteProcessModal.tsx
  src/components/molecules/VoteModalText.tsx
  src/hooks/useCopyText.ts
  src/hooks/useHtmlElement.ts
  src/store/voteLangState.ts
  src/styles/globals.css
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/vote.ts
Labels: feature

#33 [develop] fix: 언어선택해도 안 바뀌는 문제(Link -> button)
  src/components/atoms/Language.tsx
  src/utils/setLangCookie.ts
Labels: bug

#37 [develop] 현재투표수 및 가능투표수 number 추가
  src/components/modals/CommonModal.tsx
  src/components/modals/VoteBlockModal.tsx
  src/components/modals/VoteDoneModal.tsx
  src/components/modals/VoteProcessModal.tsx
  src/components/templates/VoteDetailLayout.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/vote.ts
Labels: feature

#39 [develop] 환경 변수명 변경 및 적용
  src/api/User.ts
  src/api/Vote.ts
  src/components/organisms/BusinessFormHandle.tsx
  src/pages/api/vote.ts
  src/pages/api/voteDetail.ts
  src/pages/en/votes.tsx
  src/pages/es/votes.tsx
  src/pages/in/votes.tsx
  src/pages/ja/votes.tsx
  src/pages/ko/votes.tsx
  src/pages/vi/votes.tsx
  src/pages/zh-CN/votes.tsx
  src/pages/zh-TW/votes.tsx
Labels: documentation

#40 [develop] feat: add vote modal button multi-language
  src/components/modals/VoteBlockModal.tsx
  src/components/modals/VoteDoneModal.tsx
  src/components/modals/VoteProcessModal.tsx
  src/store/voteLangState.ts
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
Labels: feature

#41 [develop] 투표 페이지 SEO 작업
  package.json
  src/components/templates/VoteDetailLayout.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/en/voteDetail.tsx
  src/pages/es/voteDetail.tsx
  src/pages/in/voteDetail.tsx
  src/pages/ja/voteDetail.tsx
  src/pages/ko/voteDetail.tsx
  src/pages/vi/voteDetail.tsx
  src/pages/zh-CN/voteDetail.tsx
  src/pages/zh-TW/voteDetail.tsx
  yarn.lock
Labels: documentation

#42 [develop] 회원가입창의 이용약관 페이지 다국어 처리
  src/components/templates/SignUpTemplate.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/textTypes.ts
Labels: documentation

#50 [develop] dynamic link 연결
  src/components/templates/VoteDetailLayout.tsx
Labels: feature

#51 [develop] 투표 페이지 신규 기능
  src/components/atoms/RankProfile.tsx
  src/components/molecules/VoteHighRankTab.tsx
  src/components/molecules/VoteTitle.tsx
  src/components/molecules/VoteTitleImage.tsx
  src/components/organisms/VoteList.tsx
  src/components/organisms/VoteListItem.tsx
  src/components/organisms/voteDetail/VoteDetailInfo.tsx
  src/components/organisms/voteDetail/VoteDetailItem.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/vote.ts
Labels: feature

#52 [develop] 투표 페이지 기능 추가 2
  src/components/organisms/VoteListItem.tsx
Labels: design

#48 [develop] 투표 페이지 UI 개선
  src/components/atoms/NavBox.tsx
  src/components/molecules/LanguageBox.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/NavContainer.tsx
  src/components/organisms/voteDetail/VoteDetailInfo.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/vi.ts
Labels: design

#53 [master] 실서버 배포
  src/components/atoms/NavBox.tsx
  src/components/atoms/RankProfile.tsx
  src/components/molecules/LanguageBox.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/NavContainer.tsx
  src/components/molecules/VoteHighRankTab.tsx
  src/components/molecules/VoteTitle.tsx
  src/components/molecules/VoteTitleImage.tsx
  src/components/organisms/VoteList.tsx
  src/components/organisms/VoteListItem.tsx
  src/components/organisms/voteDetail/VoteDetailInfo.tsx
  src/components/organisms/voteDetail/VoteDetailItem.tsx
  src/components/templates/VoteDetailLayout.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/vote.ts
Labels: feature, design

#54 [develop] 수정: 투표상세페이지에서 투표현황 비율 문제
  src/components/organisms/voteDetail/VoteDetailInfo.tsx
Labels: design

#55 [master] 투표현황 비율 조정해 실서버 배포
  src/components/organisms/voteDetail/VoteDetailInfo.tsx
Labels: design

#56 [로그인기능] 구글로그인불가모달
  src/components/modals/OtherBrowserModal.tsx
  src/components/templates/LoginTemplate.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/textTypes.ts
Labels: feature

#47 [develop] google-login 블락 처리
  src/components/modals/OtherBrowserModal.tsx
  src/components/templates/LoginTemplate.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/textTypes.ts
Labels: feature

#43 [develop] design 버그 제거
  src/components/atoms/LoginButtons/BaseLoginButton.tsx
  src/components/templates/MainPageTemplate.tsx
Labels: design

#57 [develop] 로그인 불가 모달 텍스트 오류 수정
  src/components/templates/LoginTemplate.tsx
Labels: bug

#58 [master] 구글 로그인 블락 처리 실서버로 배포
  src/components/atoms/LoginButtons/BaseLoginButton.tsx
  src/components/modals/OtherBrowserModal.tsx
  src/components/templates/LoginTemplate.tsx
  src/components/templates/MainPageTemplate.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/textTypes.ts
Labels: feature

#61 [develop] Gtm연동
  src/components/atoms/ShareButtonWithIcon.tsx
  src/components/atoms/UnstyledButton.tsx
  src/components/atoms/VoteModalButton.tsx
  src/components/modals/CommonModal.tsx
  src/components/modals/VoteBlockModal.tsx
  src/components/modals/VoteDetailShareModal.tsx
  src/components/modals/VoteDoneModal.tsx
  src/components/modals/VoteProcessModal.tsx
Labels: feature

#62 [master] gtm 버튼 클릭 이벤트 연동을 위한 id 추가
  src/components/atoms/ShareButtonWithIcon.tsx
  src/components/atoms/UnstyledButton.tsx
  src/components/atoms/VoteModalButton.tsx
  src/components/modals/CommonModal.tsx
  src/components/modals/VoteBlockModal.tsx
  src/components/modals/VoteDetailShareModal.tsx
  src/components/modals/VoteDoneModal.tsx
  src/components/modals/VoteProcessModal.tsx
Labels: feature

#59 [develop] 메인페이지 img debug 및 개선
  public/icons/icon_globe.svg
  public/icons/icon_plus.svg
  src/components/atoms/IconGlobe.tsx
  src/components/atoms/IconPlus.tsx
  src/components/molecules/LanguageBox.tsx
  src/components/organisms/Carousel.tsx
  src/components/templates/MainPageTemplate.tsx
Labels: improvements

#63 [feat/community] 커뮤니티 페이지 기초
  public/images/fanplus_logo_small.png
  src/api/Community.ts
  src/components/atoms/MainLogo.tsx
  src/components/atoms/NavBox.tsx
  src/components/molecules/CommunityBoardItem.tsx
  src/components/molecules/LanguageBox.tsx
  src/components/molecules/LanguageContainer.tsx
  src/components/molecules/NavBar.tsx
  src/components/molecules/NavContainer.tsx
  src/components/molecules/SideBar.tsx
  src/components/organisms/CommunityBoardWrapper.tsx
  src/components/organisms/Layout.tsx
  src/components/templates/CommunityPageTemplate.tsx
  src/pages/api/community/home.ts
  src/pages/en/community/board.tsx
  src/pages/en/community/index.tsx
  src/pages/es/community/board.tsx
  src/pages/es/community/index.tsx
  src/pages/in/community/board.tsx
  src/pages/in/community/index.tsx
  src/pages/ja/community/board.tsx
  src/pages/ja/community/index.tsx
  src/pages/ko/community/board.tsx
  src/pages/ko/community/index.tsx
  src/pages/vi/community/board.tsx
  src/pages/vi/community/index.tsx
  src/pages/zh-CN/community/board.tsx
  src/pages/zh-CN/community/index.tsx
  src/pages/zh-TW/community/board.tsx
  src/pages/zh-TW/community/index.tsx
  src/texts/en.ts
  src/texts/es.ts
  src/texts/in.ts
  src/texts/ja.ts
  src/texts/ko.ts
  src/texts/vi.ts
  src/texts/zh-CN.ts
  src/texts/zh-TW.ts
  src/types/community.ts
  src/types/textTypes.ts
Labels: feature

#64 [feat/community] fix: navBar 사이즈 문제
  src/components/atoms/NavBox.tsx
  src/components/molecules/LanguageBox.tsx
  src/components/molecules/SideBar.tsx
Labels: design
